Fix the transceiver CLI error due to missing functions
Error was as below when type "show interfaces transceiver presence":
TypeError: Can't instantiate abstract class SfpUtil
with abstract methods get_transceiver_change_event

See more at: https://jira01.corp.linkedin.com:8443/browse/FALCO-1845

Signed-off-by: Zhenggen Xu <zxu@linkedin.com>

    RB=1754081
    G=lnos-reviewers
    R=pchaudhary,pmao,samaity,sfardeen,zxu
    A=zxu